=== JatinMaharjan/Sneaker-Store/19032170_russiandoll.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Store">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element name="header">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Heading"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Details">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Storename"/>
              <xs:element name="Store-Address">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="Main_branch"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="Telephone-Number"/>
              <xs:element type="xs:long" name="Personal_Number"/>
              <xs:element type="xs:anyURI" name="website"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:string" name="Heading"/>
        <xs:element name="Shoes-detail">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element name="shoes-Info" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Shoes_Name"/>
                    <xs:element name="Shoes">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="type"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Shoes_Brand">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Brand: Air Jordan"/>
                                <xs:enumeration value="Brand: Addidas"/>
                                <xs:enumeration value="Brand: Balenciaga"/>
                                <xs:enumeration value="Brand: Gucci"/>
                                <xs:enumeration value="Brand: Nike"/>
                                <xs:enumeration value="Brand: Nike"/>
                                <xs:enumeration value="Brand: Air Jordan"/>
                                <xs:enumeration value="Brand: Addidas"/>
                                <xs:enumeration value="Brand: Nike"/>
                                <xs:enumeration value="Brand: Vans"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element type="xs:string" name="Release_Date"/>
                    <xs:element name="Quantity">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="Shoes_Quntity"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="Stock_Keeping_Unit"/>
                    <xs:element type="xs:string" name="Shoes_Material"/>
                    <xs:element type="xs:string" name="Main_Colour"/>
                    <xs:element type="xs:string" name="Colourway"/>
                    <xs:element type="xs:string" name="Designed_by"/>
                    <xs:element type="xs:string" name="Silhouette"/>
                    <xs:element type="xs:string" name="Technology"/>
                    <xs:element type="xs:string" name="Nick_Name"/>
                    <xs:element name="Category">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="Category"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Collaboration">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="Collaboration"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Shoe_Available">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="Available_Shoes"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="Buy_New"/>
                    <xs:element type="xs:string" name="Buy_Used"/>
                    <xs:element name="Limited_Pair">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="LimitedPairs"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Inspired_From">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="Inspired_From"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Brand">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:byte" name="Brand_id"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="description"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:byte" name="ShoesNo" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JatinMaharjan/Sneaker-Store/19032170.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Store SYSTEM "catalog_19032170.dtd">

<Store xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="19032170_russiandoll.xsd">

<header>
    
    <Heading>Jutta</Heading>
</header>

<Details >
    <Storename>Jutta</Storename>
    <Store-Address Main_branch="Bhaisepati">Khokana,Lalitpur</Store-Address>
    <Telephone-Number>01-5591345</Telephone-Number>
    <Personal_Number>9861356479</Personal_Number>
    <website>www.Jutta.com.np</website>
</Details>
<Heading>Nike</Heading>
<Shoes-detail ShoesNo="01">
    <shoes-Info>

        <Shoes_Name>Shoes Name: Air Jordan 1 Retro High OG 'Hyper Royal'</Shoes_Name>
        <Shoes type="High Top Sneaker">Shoes Type: High Top Sneaker</Shoes>
        <Shoes_Brand>Brand: Air Jordan</Shoes_Brand>
        <Release_Date>Release Date: 2021-04-18</Release_Date>
	    <Quantity Shoes_Quntity= "1000 Worldwide">Shoes Quality: 30,000 Worldwide</Quantity>
        <Stock_Keeping_Unit>SKU: 555088402</Stock_Keeping_Unit>
        <Shoes_Material>Shoes_Material: Suede</Shoes_Material>
        <Main_Colour>Main Colour: Blue</Main_Colour>
        <Colourway>Colourway: Hyper Royal/Light Smoke Grey/White</Colourway>
        <Designed_by>Peter Moore</Designed_by>
        <Silhouette>Silhouette: Air Jordan 1</Silhouette>
        <Technology>Technology: Air</Technology>
        <Nick_Name>Nick Name: Hyper Royal</Nick_Name>
        <Category Category= "Basketball">Category: Basketball</Category>
	    <Collaboration Collaboration= "Travis Scott">Collaboration: Travic Scott</Collaboration>
        <Shoe_Available Available_Shoes= "45 Pairs">Available Shoes: 45 Pairs</Shoe_Available>
        <Buy_New>Buy New: 258</Buy_New>
        <Buy_Used>Buy Used: $333</Buy_Used>
	    <Limited_Pair LimitedPairs="11/170">Limited Pair: 11/170</Limited_Pair>
        <Inspired_From Inspired_From= "Back to the Future II(Movie)">Inspired From: Back to the Future II(Movie)</Inspired_From>
        <Brand Brand_id= "2">Brand ID: 2</Brand>
        <description>
            <![CDATA[The Air Jordan 1 Retro High OG ‘Hyper Royal’ takes on a weathered aesthetic, highlighted by a white leather upper with faded blue suede overlays. Contrasting neutral grey hits land on the Swoosh and padded collar, adding to the sneaker’s understated palette. OG branding elements include a Jordan Wings logo on the lateral collar flap and a woven Nike tongue tag. The high-top is mounted on a standard AJ1 rubber cupsole, featuring encapsulated Nike Air cushioning in the heel.]]>
        </description>
        
    </shoes-Info>
</Shoes-detail>

<Heading>Addidas</Heading>
<Shoes-detail ShoesNo="02">
    <shoes-Info>

        <Shoes_Name>Shoes Name: Yeezy Boost 350 V2 'Cream White / Triple White'</Shoes_Name>
        <Shoes type="Low-Top Sneaker">Shoes Type: Low Top Sneaker</Shoes>
        <Shoes_Brand>Brand: Addidas</Shoes_Brand>
        <Release_Date>Release Date: 2017-04-30</Release_Date>
	    <Quantity Shoes_Quntity= "45,000 Worldwide">Shoes Quality: 30,000 Worldwide</Quantity>
        <Stock_Keeping_Unit>SKU: CP9366</Stock_Keeping_Unit>
        <Shoes_Material>Shoes_Material: Primeknit</Shoes_Material>
        <Main_Colour>Main Colour: White</Main_Colour>
        <Colourway>Colourway: Cream White/Cream White/Core White</Colourway>
        <Designed_by>Designed by: Kanye West</Designed_by>
        <Silhouette>Silhouette: Yeezy Boost</Silhouette>
        <Technology>Technology: Boost</Technology>
        <Nick_Name>Nick Name: Cream White</Nick_Name>
        <Category Category= "Basketball">Category: Basketball</Category>
	    <Collaboration Collaboration= "Travis Scott">Collaboration: Travic Scott</Collaboration>
	    <Shoe_Available Available_Shoes= "45 Pairs">Available Shoes: 45 Pairs</Shoe_Available>
        <Buy_New>Buy New: $374</Buy_New>
        <Buy_Used>Buy Used: $130</Buy_Used>
	    <Limited_Pair LimitedPairs="11/170">Limited Pair: 11/170</Limited_Pair>
        <Inspired_From Inspired_From= "Back to the Future II(Movie)">Inspired From: Back to the Future II(Movie)</Inspired_From>
        <Brand Brand_id= "1">Brand ID: 1</Brand>
        <description>
            <![CDATA[First released on April 29, 2017, the Yeezy Boost 350 V2 ‘Cream White’ combines a cream Primeknit upper with tonal cream SPLY 350 branding, and a translucent white midsole housing full-length Boost. Released again in October 2018, this retro helped fulfill Kanye West’s oft-repeated ‘YEEZYs for everyone’ Twitter mantra, as adidas organized the biggest drop in Yeezy history by promising pre-sale to anyone who signed up on the website. Similar to the first release, the ‘Triple White’ 2018 model features a Primeknit upper, a Boost midsole and custom adidas and Yeezy co-branding on the insole.]]>
        </description>
    </shoes-Info>
</Shoes-detail>

<Heading>Balenciaga</Heading>
<Shoes-detail ShoesNo="03">
    <shoes-Info>

        <Shoes_Name>Shoes Name: Balenciaga Speed Trainer 'Clear Sole - Black'</Shoes_Name>
        <Shoes type="High Top Sneaker">Shoes Type: High Top Sneaker</Shoes>
        <Shoes_Brand>Brand: Balenciaga</Shoes_Brand>
        <Release_Date>Release Date: November 2016</Release_Date>
	    <Quantity Shoes_Quntity= "30 Worldwide">Shoes Quality: 30,000 Worldwide</Quantity>
        <Stock_Keeping_Unit>SKU: W05GG 1010</Stock_Keeping_Unit>
        <Shoes_Material>Shoes_Material: Polyamide</Shoes_Material>
        <Main_Colour>Main Colour: Black</Main_Colour>
        <Colourway>Colourway: Black/White</Colourway>
        <Designed_by>Designed by: Demna Gvasalia</Designed_by>
        <Silhouette>Silhouette: Balenciaga Speed Trainers</Silhouette>
        <Technology>Technology: Boost</Technology>
        <Nick_Name>Nick Name: Clear Sole-Black</Nick_Name>
	    <Category Category= "Basketball">Category: Basketball</Category>
	    <Collaboration Collaboration= "Travis Scott">Collaboration: Travic Scott</Collaboration>
        <Shoe_Available Available_Shoes="50 Pairs">Available Shoes: 50 Pairs</Shoe_Available>
        <Buy_New>Buy New: $610</Buy_New>
        <Buy_Used>Buy Used: $150</Buy_Used>
	    <Limited_Pair LimitedPairs="11/170">Limited Pair: 11/170</Limited_Pair>
        <Inspired_From Inspired_From= "Back to the Future II(Movie)">Inspired From: Back to the Future II(Movie)</Inspired_From>
        <Brand Brand_id= "1">Brand ID: 1</Brand>
        <description>
            <![CDATA[Balenciaga is the neat and classy look shoes. Is is a proff that there is beauty in simplicity. It is insane comfortable with memory foam to boast and shock-absorbing components to keep the feet relaxed.]]>
        </description>
    </shoes-Info>
</Shoes-detail>

<Heading>Gucci</Heading>

<Shoes-detail ShoesNo="04">
    <shoes-Info>

        <Shoes_Name>Shoes Name: Gucci Ace Stripe Leather 'Black'</Shoes_Name>
        <Shoes type="High Top Sneaker">Shoes Type: Low Top Sneaker</Shoes>
        <Shoes_Brand>Brand: Gucci</Shoes_Brand>
        <Release_Date>Release Date: 2017</Release_Date>
	    <Quantity Shoes_Quntity= "3,000 Worldwide">Shoes Quality: 30,000 Worldwide</Quantity>
        <Stock_Keeping_Unit>SKU: 523469 0FIV0 1076</Stock_Keeping_Unit>
        <Shoes_Material>Shoes_Material: Leather</Shoes_Material>
        <Main_Colour>Main Colour: Black</Main_Colour>
        <Colourway>Colourway: Black/Red</Colourway>
        <Designed_by>Designed by: Marco Bizzarri</Designed_by>
        <Silhouette>Silhouette: Gucci Ace</Silhouette>
        <Technology>Technology: Vintage</Technology>
        <Nick_Name>Nick Name: Black</Nick_Name>
	    <Category Category= "Basketball">Category: Basketball</Category>
	    <Collaboration Collaboration= "Travis Scott">Collaboration: Travic Scott</Collaboration>
	    <Shoe_Available Available_Shoes= "45 Pairs">Available Shoes: 45 Pairs</Shoe_Available>
        <Buy_New>Buy New: $415</Buy_New>
        <Buy_Used>Buy Used: $460</Buy_Used>
        <Limited_Pair LimitedPairs="11/170">Limited Pair: 11/170</Limited_Pair>
        <Inspired_From Inspired_From= "Back to the Future II(Movie)">Inspired From: Back to the Future II(Movie)</Inspired_From>
        <Brand Brand_id= "91">Brand ID: 1</Brand>
        <description>
            <![CDATA[Gucci is an italian fashion label founded in 1921 by Guccio Gucci. It is one of the oldest italian fashion brand. This brand produce luxury goods. This shoes is the vintage shoes.]]>
        </description>
    </shoes-Info>
</Shoes-detail>

<Heading>Nike</Heading>
<Shoes-detail ShoesNo="05">
    <shoes-Info>

        <Shoes_Name>Shoes Name: LeBron 17 'Air Command Force'</Shoes_Name>
        <Shoes type="High Top Sneaker">Shoes Type: High Top Sneaker</Shoes>
        <Shoes_Brand>Brand: Nike</Shoes_Brand>
        <Release_Date>Release Date: 2020-04-17</Release_Date>
	    <Quantity Shoes_Quntity= "30,00 Worldwide">Shoes Quality: 30,000 Worldwide</Quantity>
        <Stock_Keeping_Unit>SKU: BQ3177 100</Stock_Keeping_Unit>
        <Shoes_Material>Shoes_Material: Kintposite</Shoes_Material>
        <Main_Colour>Main Colour: White</Main_Colour>
        <Colourway>Colourway: White/Black/Multi-Color</Colourway>
        <Designed_by>Designed by: Jason Petrie</Designed_by>
        <Silhouette>Silhouette: LeBron 17</Silhouette>
        <Technology>Technology: Air</Technology>
        <Nick_Name>Nick Name: Air Command Force</Nick_Name>
        <Category Category= "Basketball">Category: Basketball</Category>
	    <Collaboration Collaboration= "Travis Scott">Collaboration: Travic Scott</Collaboration>
	    <Shoe_Available Available_Shoes= "45 Pairs">Available Shoes: 45 Pairs</Shoe_Available>
        <Buy_New>Buy New: $100</Buy_New>
        <Buy_Used>Buy Used: $120</Buy_Used>
	    <Limited_Pair LimitedPairs="11/170">Limited Pair: 11/170</Limited_Pair>
        <Inspired_From Inspired_From= "Back to the Future II(Movie)">Inspired From: Back to the Future II(Movie)</Inspired_From>
        <Brand Brand_id= "1">Brand ID: 1</Brand>
        <description>
